---
title: "International collaboration shapes global researcher mobility across diverse socioeconomic contexts"
output: html_document
date: "2023-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 


```{r}
library("ggplot2")
library("dplyr")
library("tidyr")
library("scales")
library("ggrepel")
library("gridExtra")
library("grid")
library("maps")
```


```{r}
researcher_first_year<-read.csv("C:/Users/geh1/OneDrive - Universiteit Leiden/Desktop/Project of PhD/previous collaboration and future mobility/Journal paper_2023/1b/n of researchers--first year.csv",header=T,sep=',',stringsAsFactors = FALSE,na.strings = "")

researcher_first_year_long<-researcher_first_year %>%
  pivot_longer(cols = c(n_researcher, n_researcher_at_least_2_pub), names_to = "variable",
               values_to = "value")

```

```{r}

png(file="Fig QSS1--first year--researchers_2023.png", width=3000,height=1500)  
ggplot(researcher_first_year, aes(x = first_year, y = n_researcher)) +
  geom_line(size = 4,color="#1f77b4") +  
  geom_point(size = 4,color="#1f77b4") +   
  scale_y_continuous(limits= c(0,1020000)
                     ,breaks=c(0, 200000,400000,600000,800000,1000000)
                     ,labels=c("0","200,000","400,000","600,000","800,000","1,000,000"))+
  scale_x_continuous(limits=c(1990,2019),breaks=seq(1990, 2019,5))+
  labs(x = "Year",
       y = "Number of researchers (published first paper)") +
   theme_bw() +
    theme( 
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0.05, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size=50),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.line.y=element_line(size=1.5,color='black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    legend.text = element_text(size = 50),
    legend.title = element_blank(),
    legend.position = c(0.3, 0.95),
    legend.key.size = unit(1, "cm")
  )
dev.off()
```


```{R}
mobi_rate_country <-read.csv("C:/Users/geh1/OneDrive - Universiteit Leiden/Desktop/Project of PhD/previous collaboration and future mobility/Journal paper_2023/1b/mobility rate--country--2023--more than 500.csv") 

is.numeric(mobi_rate_country$MR_c)
is.numeric(mobi_rate_country$MR_nc)
country_code_15<-c(
        "US",
        "CN",
        "UK",
        "DE",
        "FR",
        "JP",
        "IT",
        "CA",
        "IN",
        "ES",
        "AU",
        "NL",
        "BR",
        "KR",
        "CH")
color <- c( 
     "#1f77b4",
     "#ff7f0e",
     "#2ca02c",
     "#d62728",
     "#9467bd",
     "#8c564b",
     "#e377c2",
     "#FBD63C",
     "#bcbd22",
     "#17becf",
     "#aec7e8",
     "#ffbb78",
     "#98df8a",
     "#ff9896",
     "#008080")
country_style <- data.frame(country_code_15, color)
country_style$shape <- 16
 
mobi_rate_country <-
  merge(mobi_rate_country,
        country_style,
        by.x = "country_code",
        by.y = "country_code_15",
        all.x = TRUE)

mobi_rate_country $color[is.na(mobi_rate_country $color)] <- "#6c757d"
mobi_rate_country $shape[is.na(mobi_rate_country $shape)] <- 1

mobi_rate_country $size <- mobi_rate_country $r_mobi / 100

mobi_rate_country $size[mobi_rate_country $size < 10] <- 6

mobi_rate_country %>%
  arrange(desc(r_mobi))
```



```{r}


median(mobi_rate_country_p$MRo_nc)
       median(mobi_rate_country_p$MRo_c)
png(file="Fig QSS3--mobility ratio--country level 2019.png", width=1500,height=1500)
 
  mobi_rate_country_p <-mobi_rate_country  %>% arrange(shape, desc(r_mobi)) %>% mutate(size_scale =scales::rescale(size, to = c(5, 50)))

    ggplot(mobi_rate_country_p,
           aes(x = MRo_nc, y =  MRo_c)) +
    xlim(0, 0.34) +
    ylim(0, 0.34) +
    labs(x = "Mobility rate amonog researchers without internaiontal collaboration (MRo_nc)") + 
    labs(y = "Mobility rate amonog researchers with internaiontal collaboration (MRo_c)") +
    geom_abline(
      intercept = 0,
      slope = 1,
      linetype = 1,
      color = "#dde5b6",
      size = 1
    ) +
    geom_vline(
      xintercept = median(mobi_rate_country_p$MRo_nc),
      linetype = "dashed",
      color = "grey",
      size = 1.2
    ) +
    geom_hline(
      yintercept = median(mobi_rate_country_p$MRo_c),
      linetype = "dashed",
      color = "grey",
      size = 1.2
    ) +
       geom_point(
      colour = mobi_rate_country_p$color,
      size = mobi_rate_country_p$size_scale,
      shape = mobi_rate_country_p$shape
    )+
       
    geom_text_repel(aes(label=ifelse(mobi_rate_country_p$size_scale>10.5 & mobi_rate_country_p$country_code!="CA" &
                                       mobi_rate_country_p$country_code!="UK" 
                                     ,as.character(mobi_rate_country_p$country_code),'')),hjust=0.5,
              vjust=0.5,size=10)+
      geom_text_repel(aes(label = ifelse(mobi_rate_country_p$country_code == "UK", 
                                   "UK", '')),  hjust = 0, vjust = 1, size = 10)+
      geom_text_repel(aes(label = ifelse(mobi_rate_country_p$country_code == "CA", 
                                   "CA", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "KR", 
                                   "KR", '')),  hjust = 0, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "CH", 
                                   "CH", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "LB", 
                                   "LB", '')),  hjust = 0.5, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "JO", 
                                   "JO", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "GH", 
                                   "GH", '')),  hjust = 0.5, vjust = 0, size = 10)+

              geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "IS", 
                                   "IS", '')),  hjust = 1, vjust = 1, size = 10)+
    geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "ZW", 
                                   "ZW", '')),  hjust = 1, vjust = 1, size = 10)+
          geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "OM", 
                                   "OM", '')),  hjust = 1, vjust = 1, size = 10)+
      
            geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "KW", 
                                   "KW", '')),  hjust = 1, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "VN", 
                                   "VN", '')),  hjust = 0, vjust = 0, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "SA", 
                                   "SA", '')),  hjust = 0, vjust = 1, size = 10)+
            geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "TH", 
                                   "TH", '')),  hjust = 1, vjust = 0, size = 10)+
    scale_size(range = c(0, 15)) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 30),
      axis.text = element_text(size = 30),
      axis.title.x = element_text(size = 30,margin=margin(20,0,20,0)),
      axis.title.y = element_text(size = 30,margin=margin(0,20,0,20))
    )

dev.off()
```
```{r}
top15_country<-c("JP", "RU", "CN", "ES", "BR", "KR", "US", "IN", "DE", "IT", "UK", "NL", "CA", "FR", "AU")
mobi_rate_country_15 <- mobi_rate_country [mobi_rate_country $country_code %in% top15_country, c("country_code","MRo_c", "MRo_nc","CMR_o")]

mobi_rate_country_15_long <- mobi_rate_country_15 %>%
  pivot_longer(cols = c(MRo_nc, MRo_c), names_to = "variable", values_to = "value")

```


```{r}

png(file="Fig QSS4--Top15.png", width=2500, height=1000)

ggplot(mobi_rate_country_15_long, aes(x = factor(country_code, levels = c("JP", "RU", "CN", "ES", "BR", "KR", "US", "IN", "DE", "IT", "UK", "NL", "CA", "FR", "AU")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("MRo_nc" = "#d62728", "MRo_c" = "#1f77b4")) +
  geom_point(data = mobi_rate_country_15, aes(x = country_code, y = CMR_o / 10, color = "CMR_o"), size = 10, shape = 23, fill = "black") + 
  
  scale_y_continuous(
    name = "Mobility rate", limits = c(0, 0.42), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4),
    sec.axis = sec_axis(~.*10, breaks = seq(0, 4, 0.5), name = "CMR_o")
  ) +

  scale_color_manual(values = c("MRo_nc" = "#d62728", "MRo_c" = "#1f77b4","CMR_o" = "black")) +
  
  labs(x = "Country code") +
  guides(
    fill = guide_legend(title = NULL, nrow = 1),
    color = guide_legend(title = NULL, nrow = 1)
  ) + 

  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title = element_text(hjust = 0.5, size = 40),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 40),
    axis.title = element_text(size = 40),
    axis.title.x = element_text(size = 40, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 40, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 35),
    legend.position = c(0.91, 0.92)
    )

dev.off()
```
```{r}
world_map <- map_data("world")
world_map <- world_map %>%
  filter(region != "Antarctica")


CMR_o_world <- world_map %>%
  left_join(mobi_rate_country, by = c("region" = "nation_map"))

```


```{r}

cmr_min <- min(CMR_o_world$CMR_o, na.rm = TRUE)
cmr_max <- max(CMR_o_world$CMR_o, na.rm = TRUE)
# 设定色带节点，0.8为最蓝，1为白，2为较浅红，最大值为最红
color_nodes <- c(0.7, 1, 2, cmr_max)
value_nodes <- scales::rescale(color_nodes, to = c(0,1), from = c(cmr_min, cmr_max))


png(file="Fig QSS--A1--world map--CMR_o--2023.png", width=3000,height=1500) 
ggplot(CMR_o_world, aes(x = long, y = lat, group = group, fill = CMR_o)) +
  geom_polygon(color = "black") +
  scale_fill_gradientn( colours = c("#1f77b4", "#ffcccc", "#fd9898", "#d62728"), # 深蓝-白-浅红-深红
                      values = value_nodes,         # 分割点
                      na.value = "grey90",
                      name = "CMR_o") +
  coord_fixed(ratio = 1.3)+
    theme_bw() +
   theme(
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0.05, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size = 40),
    axis.ticks = element_blank(), 
    axis.line = element_blank(),  
    axis.text = element_blank(),  
    axis.title = element_blank(),  
    legend.position = c(0.08, 0.50),  
    legend.title = element_text(size = 50),  
    legend.text = element_text(size = 50),    
    legend.key.size = unit(3, "cm") 
  )

dev.off()
```


```{r}

mobi_rate_region_summary <- mobi_rate_country %>%
  group_by(region) %>%
  summarise(
    mean_MRo_c   = mean(MRo_c, na.rm = TRUE),
    mean_MRo_nc  = mean(MRo_nc, na.rm = TRUE),
    .groups = "drop"  
  )

mobi_rate_region_summary_long <- mobi_rate_region_summary %>%
  pivot_longer(cols = c(mean_MRo_nc, mean_MRo_c), names_to = "variable", values_to = "value")

mobi_rate_country_region_no_NA<- mobi_rate_country %>%  filter(region != '#N/A' )

mobi_rate_country_region_no_NA %>% # filter (country_code=='MA') 
  filter(region %in% c('East Asia & Pacific')), 'Middle East & North Africa','South Asia') )

mobi_rate_country_region_no_NA %>% 
  group_by(region) %>% 
  summarise(mean_cmro=mean(CMR_o, na.rm = TRUE)
            ) %>%
  arrange(desc(mean_cmro))

```


```{r}
plot_mobi_rate_region<-ggplot(mobi_rate_region_summary_long, aes(x = factor(region, levels = c("East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa","North America","South Asia", "Sub-Saharan Africa")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4"),
                    labels = c("mean_MRo_nc" = "Without prior international collaboration (MRo_nc)", 
                      "mean_MRo_c" = "With prior international collaboration (MRo_c)")) +
  
  scale_y_continuous(
    name = "Average mobility rate", limits = c(0, 0.27), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2,0.25)
  ) +
    scale_x_discrete(breaks = c( "East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa",
                                 "North America","South Asia","Sub-Saharan Africa"),
                     labels=c("EAP", "ECA", "LAC","MENA", "NA","SA","SSA")
                                )+
  scale_color_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4")) +
  
  labs(x = "Region of origin country") +
  guides(
    fill = guide_legend(title = NULL, ncol= 1),
    color = guide_legend(title = NULL, ncol = 1)
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),

    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 50),
    legend.position = c(0.6, 0.98)
  ) +
  ggtitle("a")

plot_mobi_rate_region_box<-ggplot(mobi_rate_country_region_no_NA,aes(x=factor(region,levels=c("East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa","North America","South Asia","Sub-Saharan Africa")),y=CMR_o,fill = region))+
  geom_violin(size=2,width = 0.5,outlier.size=8)+
  geom_boxplot(size = 1.5, width = 0.2,outlier.size=8) +
  stat_boxplot(geom = "errorbar",size=3,width=0.2)+
  scale_fill_manual(values = c( 
    "East Asia & Pacific"="#1F77B4", 
                   "Europe & Central Asia"="#FF7F0E", 
                   "Latin America & Caribbean"="#2CA02C", 
                   "Middle East & North Africa"="#D62728", 
                   "North America"="#9467BD", 
                   "South Asia"= "#8c564b",
                   "Sub-Saharan Africa" = "#eeee00")) +
  

  stat_summary(fun=mean, geom="point", shape=23, size=15, fill="black")+
  guides(fill="none")+

  scale_y_continuous(limits= c(0,4),breaks=seq(0, 4,0.5))+
  scale_x_discrete(breaks = c(  "East Asia & Pacific", "Europe & Central Asia"
                                ,"Latin America & Caribbean","Middle East & North Africa"
                                ,"North America","South Asia","Sub-Saharan Africa"),
                   labels=c("EAP", "ECA", "LAC","MENA", "NA","SA","SSA")
                     )+
  xlab("Region of origin country")+
  ylab("Collaboration Mobility Ratio (CMR_o)")+

  theme_bw() +
    theme( legend.position = "none",

    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size=50),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.line.y=element_line(size=1.5,color='black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(30, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 30, 0, 0))

  )+
  ggtitle("b")


```


```{r}


mobi_rate_income_summary <- mobi_rate_country %>%
  group_by(income_group) %>%
  summarise(
    mean_MRo_c   = mean(MRo_c, na.rm = TRUE),
    mean_MRo_nc  = mean(MRo_nc, na.rm = TRUE),
    .groups = "drop" 
  )


mobi_rate_income_summary_long <- mobi_rate_income_summary   %>%
  pivot_longer(cols = c(mean_MRo_nc, mean_MRo_c), names_to = "variable", values_to = "value")

mobi_rate_country_income_no_NA<- mobi_rate_country %>%  filter(income_group != '#N/A')

```

```{r}
plot_mobi_rate_income<-ggplot(mobi_rate_income_summary_long  , aes(x = factor(income_group, levels = c("High", "Upper middle", "Lower middle", "Low")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4")) +

  scale_color_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4","CMR_o" = "black")) +
  scale_x_discrete(breaks = c( "High", "Upper middle", "Lower middle", "Low"),
                     labels=c("H", "UM", "LM", "L")
                                )+
  scale_y_continuous(
    name = "Average mobility rate", limits = c(0, 0.27), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2,0.25)
  ) +
  labs(x = "Income group of origin country") +
  labs(y="Mobility rate")+
  guides(
    fill = guide_legend(title = NULL, ncol = 1),
    color = guide_legend(title = NULL, ncol = 1)
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),

    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 50),
    legend.position = "none"
  )+
  ggtitle("c")


plot_mobi_rate_income_box<-ggplot(mobi_rate_country_income_no_NA, aes(x = factor(income_group,levels = c("High", "Upper middle", "Lower middle", "Low")), y = CMR_o,fill = income_group)) +
  geom_violin(size=2,width = 0.5,outlier.size=8)+
  geom_boxplot(size = 1.5, width = 0.2,outlier.size=8) +
  stat_boxplot(geom = "errorbar",size=3,width=0.2)+
  
  scale_fill_manual(values = c(
    "High" = "#1f77b4",
    "Upper middle" = "#ff7f0e",
    "Lower middle" = "#2ca02c",
    "Low" = "#d62728"
  )) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 15, fill = "black") +
  guides(fill = "none") +
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5)) +
  scale_x_discrete(breaks = c("High", "Upper middle", "Lower middle", "Low"),
                   labels = c("H", "UM", "LM", "L")) +
  xlab("Income group of origin country") +
   ylab("Collaboration Mobility Ratio (CMR_o)")+
  theme_bw() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size = 50),
    axis.ticks = element_line(size = 1.5),
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5),
    axis.text = element_text(size = 50),
    axis.line.y = element_line(size = 1.5, color = 'black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(30, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 30, 0, 0))
  ) +
  ggtitle("d")

```

```{r}
grid_layout <- rbind(
  c(1, 1, 1, 3, 3,3),
  c(1, 1, 1, 3, 3,3),
  c(2, 2, 2, 4, 4,4),
  c(2, 2, 2, 4, 4,4)
)
png(file="Fig QSS5--mobility rate_2023.png", width=3750,height=3000) 

grid.arrange(plot_mobi_rate_region,plot_mobi_rate_income,plot_mobi_rate_region_box, plot_mobi_rate_income_box,layout_matrix = grid_layout)

dev.off()

```


```{r}

CMR_region_income_summary <- mobi_rate_country %>%
  group_by(region, income_group) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n(),
            .groups = "drop"
            )

CMR_income_summary <- mobi_rate_country %>%
  group_by(income_group) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n()) %>%
  mutate(region = "Average")


CMR_region_summary <- mobi_rate_country %>%
  group_by(region) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n()) %>%
  mutate(income_group = "Average")

CMR_region_income<-bind_rows(CMR_region_income_summary , CMR_income_summary, CMR_region_summary)

CMR_region_income<- CMR_region_income %>%
  mutate(label = paste0(round(mean_CMR_o, 2), " (", country_count, ")"))

total_mean_CMR_o <- mean(CMR_region_income$mean_CMR_o, na.rm = TRUE)
total_id_count <- nrow(CMR_region_income)

median_value_region_income <- median(CMR_region_income$mean_CMR_o, na.rm = TRUE)

```


```{r}
png(file="Fig QSS--A2--mobility rate--region and income.png", width=1500,height=500)


ggplot(CMR_region_income, aes(
  x = factor(income_group, levels = c("High", "Upper middle", "Lower middle", "Low","Average")),
  y = factor(region, levels = c("Average", "East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa",
                                 "North America","South Asia","Sub-Saharan Africa")), fill = mean_CMR_o)) +
  
   geom_tile(aes(fill = ifelse(income_group == "Average" | region == "Average", NA, mean_CMR_o)), color = "white") +
  geom_tile(data = subset(CMR_region_income, income_group == "Average" | region == "Average"), fill = "white", color = "white") +
  geom_text(aes(label = label), color = "black", size = 8, 
            hjust = 0.5, vjust = 0.5) +
  scale_fill_gradient2(low = "#ffffe0",  high = "#d62728")+
  labs( x = "Income group", y = "Region",fill = "mean_CMR_o")+
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title = element_text(hjust = 0.5, size = 40),
    axis.ticks = element_blank(), 
    axis.ticks.length = unit(0, "cm"), 
    axis.text = element_text(size = 30),
    axis.title = element_blank(),
    axis.title.x = element_text(size = 30, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 30, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 30),
      legend.title = element_blank(),
     # legend.title.align = 0.1,
    legend.key.size = unit(1, "cm"),           
    legend.key.width = unit(0.5, "cm"),       
    legend.key.height = unit(2, "cm")  ,     
      legend.position = "right"
  )
dev.off()
```