---
title: "International collaboration shapes global researcher mobility across diverse socioeconomic contexts"
output: html_document
date: "2023-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 


```{r}
library("ggplot2")
library("dplyr")
library("tidyr")
library("scales")
library("ggrepel")
library("gridExtra")
library("grid")
library("maps")
```


```{r}
# Read data from CSV: the annual number of disambiguated researchers who published their first paper in the Dimensions database (1990–2019)
researcher_first_year<-read.csv("n of researchers--first year.csv",header=T,sep=',',stringsAsFactors = FALSE,na.strings = "")

```

```{r}
#Drew Fig.1
png(file="Fig QSS1--first year--researchers_2023.png", width=3000,height=1500)  
ggplot(researcher_first_year, aes(x = first_year, y = n_researcher)) +
  geom_line(size = 4,color="#1f77b4") +  
  geom_point(size = 4,color="#1f77b4") +   
  scale_y_continuous(limits= c(0,1020000)
                     ,breaks=c(0, 200000,400000,600000,800000,1000000)
                     ,labels=c("0","200,000","400,000","600,000","800,000","1,000,000"))+
  scale_x_continuous(limits=c(1990,2019),breaks=seq(1990, 2019,5))+
  labs(x = "Year of first publication",
       y = "Number of researchers (published first paper)") +
   theme_bw() +
    theme( 
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0.05, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size=50),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.line.y=element_line(size=1.5,color='black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    legend.text = element_text(size = 50),
    legend.title = element_blank(),
    legend.position = c(0.3, 0.95),
    legend.key.size = unit(1, "cm")
  )
dev.off()
```


```{r}
# Read country-level mobility data from CSV

mobi_rate_country <-read.csv("mobility rate--country--2023--more than 500.csv") 

is.numeric(mobi_rate_country$MR_c)
is.numeric(mobi_rate_country$MR_nc)

# Define 15 country codes with most outgoing researchers and corresponding colors
country_code_15<-c(
        "US",
        "CN",
        "UK",
        "DE",
        "FR",
        "JP",
        "IT",
        "CA",
        "IN",
        "ES",
        "AU",
        "NL",
        "BR",
        "KR",
        "CH")
color <- c( 
     "#1f77b4",
     "#ff7f0e",
     "#2ca02c",
     "#d62728",
     "#9467bd",
     "#8c564b",
     "#e377c2",
     "#FBD63C",
     "#bcbd22",
     "#17becf",
     "#aec7e8",
     "#ffbb78",
     "#98df8a",
     "#ff9896",
     "#008080")

# Create a data frame for country style (color and shape)
country_style <- data.frame(country_code_15, color)
country_style$shape <- 15

# Merge color and shape info into mobility data by country code
mobi_rate_country <-
  merge(mobi_rate_country,
        country_style,
        by.x = "country_code",
        by.y = "country_code_15",
        all.x = TRUE)

# Assign default color and shape to countries not in the 15
mobi_rate_country $color[is.na(mobi_rate_country $color)] <- "#6c757d"
mobi_rate_country $shape[is.na(mobi_rate_country $shape)] <- 1

# Set plot size based on 'r_mobi' (n of outgoing researchers) value
mobi_rate_country $size <- mobi_rate_country $r_mobi / 100

mobi_rate_country $size[mobi_rate_country $size < 10] <- 5

```
```{r}
fit <- manova(cbind(MRo_c, MRo_nc) ~ region, data = mobi_rate_country)
summary(fit)

summary.aov(fit)

TukeyHSD(aov(MRo_c ~ region, data=mobi_rate_country))
TukeyHSD(aov(MRo_nc ~ region, data=mobi_rate_country))
```

```{r}
# Save the scatter plot (Fig. 3) as a PNG image
png(file="Fig QSS3--mobility ratio--country level 2019.png", width=1500,height=1500)

# Arrange data and scale point sizes for visualization 
  mobi_rate_country_p <-mobi_rate_country  %>% arrange(shape, desc(r_mobi)) %>% mutate(size_scale =scales::rescale(size, to = c(5, 50)))

# Create scatter plot comparing mobility rates with and without international collaboration

    ggplot(mobi_rate_country_p,
           aes(x = MRo_nc, y =  MRo_c)) +
    xlim(0, 0.34) +
    ylim(0, 0.34) +
    labs(x = "Mobility rate amonog researchers without internaiontal collaboration (MRo_nc)") + 
    labs(y = "Mobility rate amonog researchers with internaiontal collaboration (MRo_c)") +
    geom_abline(
      intercept = 0,
      slope = 1,
      linetype = 1,
      color = "#dde5b6",
      size = 1
    ) +
    geom_vline(
      xintercept = median(mobi_rate_country_p$MRo_nc),
      linetype = "dashed",
      color = "grey",
      size = 1.2
    ) +
    geom_hline(
      yintercept = median(mobi_rate_country_p$MRo_c),
      linetype = "dashed",
      color = "grey",
      size = 1.2
    ) +
       geom_point(
      colour = mobi_rate_country_p$color,
      size = mobi_rate_country_p$size_scale,
      shape = mobi_rate_country_p$shape
    )+
  
# Label selected countries      
    geom_text_repel(aes(label=ifelse(mobi_rate_country_p$size_scale>10.5 & mobi_rate_country_p$country_code!="CA" &
                                       mobi_rate_country_p$country_code!="UK" 
                                     ,as.character(mobi_rate_country_p$country_code),'')),hjust=0.5,
              vjust=0.5,size=10)+
      geom_text_repel(aes(label = ifelse(mobi_rate_country_p$country_code == "UK", 
                                   "UK", '')),  hjust = 0, vjust = 1, size = 10)+
      geom_text_repel(aes(label = ifelse(mobi_rate_country_p$country_code == "CA", 
                                   "CA", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "KR", 
                                   "KR", '')),  hjust = 0, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "CH", 
                                   "CH", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "LB", 
                                   "LB", '')),  hjust = 0.5, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "JO", 
                                   "JO", '')),  hjust = 1, vjust = 1, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "GH", 
                                   "GH", '')),  hjust = 0.5, vjust = 0, size = 10)+

              geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "IS", 
                                   "IS", '')),  hjust = 1, vjust = 1, size = 10)+
    geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "ZW", 
                                   "ZW", '')),  hjust = 1, vjust = 1, size = 10)+
          geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "OM", 
                                   "OM", '')),  hjust = 1, vjust = 1, size = 10)+
      
            geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "KW", 
                                   "KW", '')),  hjust = 1, vjust = 0, size = 10)+
        geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "VN", 
                                   "VN", '')),  hjust = 0, vjust = 0, size = 10)+
      geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "SA", 
                                   "SA", '')),  hjust = 0, vjust = 1, size = 10)+
            geom_text(aes(label = ifelse(mobi_rate_country_p$country_code == "TH", 
                                   "TH", '')),  hjust = 1, vjust = 0, size = 10)+
    scale_size(range = c(0, 15)) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 30),
      axis.text = element_text(size = 30),
      axis.title.x = element_text(size = 30,margin=margin(20,0,20,0)),
      axis.title.y = element_text(size = 30,margin=margin(0,20,0,20))
    )

dev.off() # Close and save the plot
```


```{r}
# Define the top 15 countries with most original researchers
top15_country<-c("JP", "RU", "CN", "ES", "BR", "KR", "US", "IN", "DE", "IT", "UK", "NL", "CA", "FR", "AU")

# Select only the top 15 countries and relevant columns from the data
mobi_rate_country_15 <- mobi_rate_country [mobi_rate_country $country_code %in% top15_country, c("country_code","MRo_c", "MRo_nc","CMR_o")]

# Reshape data to long format for plotting (combine MRo_c and MRo_nc into one column)
mobi_rate_country_15_long <- mobi_rate_country_15 %>%
  pivot_longer(cols = c(MRo_nc, MRo_c), names_to = "variable", values_to = "value")

```


```{r}
# Save the bar plotn (Fig. 4) as a PNG image
png(file="Fig QSS4--Top15.png", width=2500, height=1000)

# Create grouped bar plot for mobility rates (with/without international collaboration) in top 15 countries

ggplot(mobi_rate_country_15_long, aes(x = factor(country_code, levels = c("JP", "RU", "CN", "ES", "BR", "KR", "US", "IN", "DE", "IT", "UK", "NL", "CA", "FR", "AU")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("MRo_nc" = "#d62728", "MRo_c" = "#1f77b4"),
                    , labels = c("MRo_nc" = "Without prior international collaboration (MRo_nc)", 
                      "MRo_c" = "With prior international collaboration (MRo_c)")) +
  
    # Add a point for CMR_o, rescaled to fit the left y-axis
  geom_point(data = mobi_rate_country_15, aes(x = country_code, y = CMR_o / 10, color = "CMR_o"), size = 10, shape = 23, fill = "black") + 
  
    # Set left y-axis for mobility rate and right axis for CMR_o
  scale_y_continuous(
    name = "Mobility rate", limits = c(0, 0.42), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4),
    sec.axis = sec_axis(~.*10, breaks = seq(0, 4, 0.5), name = "Collaboration Mobility Ratio (CMR_o)")
  ) +
  # Set color for CMR_o points
  scale_color_manual(values = c("MRo_nc" = "#d62728", "MRo_c" = "#1f77b4","CMR_o" = "black")) +
  
  labs(x = "Country code") +
  # Combine legends for bar and point, set layout
  guides(
    fill = guide_legend(title = NULL, nrow = 2),
    color = guide_legend(title = NULL, nrow = 1)
  ) + 
  # Theme settings for cleaner and bigger labels
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title = element_text(hjust = 0.5, size = 40),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 40),
    axis.title = element_text(size = 40),
    axis.title.x = element_text(size = 40, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 40, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 35),
    legend.position = c(0.81, 0.92)
    )

dev.off() # Finish and save the plot
```


```{r}
# Load world map data
world_map <- map_data("world")

# Remove Antarctica from the map
world_map <- world_map %>%
  filter(region != "Antarctica")

# Merge map data with mobility data by matching country names
CMR_o_world <- world_map %>%
  left_join(mobi_rate_country, by = c("region" = "nation_map"))

```


```{r}
# Find min and max CMR_o values (ignoring missing values)
cmr_min <- min(CMR_o_world$CMR_o, na.rm = TRUE)
cmr_max <- max(CMR_o_world$CMR_o, na.rm = TRUE)

# Define color breakpoints for the color scale
color_nodes <- c(cmr_min, 1, 2, cmr_max)
value_nodes <- scales::rescale(color_nodes, to = c(0,1), from = c(cmr_min, cmr_max))

# Save the map as a PNG image (Fig. A1)
png(file="Fig QSS--A1--world map--CMR_o--2023.png", width=3000,height=1500) 
ggplot(CMR_o_world, aes(x = long, y = lat, group = group, fill = CMR_o)) +
  geom_polygon(color = "black") + # Draw country borders
  scale_fill_gradientn( colours = c("#1f77b4", "#ffcccc", "#fd9898", "#d62728"),  # Custom color palette
                      values = value_nodes,         
                      na.value = "grey90",
                      name = "CMR_o") +
  coord_fixed(ratio = 1.3)+
    theme_bw() +
   theme(
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0.05, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size = 40),
    axis.ticks = element_blank(), 
    axis.line = element_blank(),  
    axis.text = element_blank(),  
    axis.title = element_blank(),  
    legend.position = c(0.08, 0.50),  
    legend.title = element_text(size = 50),  
    legend.text = element_text(size = 50),    
    legend.key.size = unit(3, "cm") 
  )

dev.off()  # Finish and save the image
```


```{r}
# Calculate mean mobility rates (with and without international collaboration)by region

mobi_rate_region_summary <- mobi_rate_country %>%
  group_by(region) %>%
  summarise(
    mean_MRo_c   = mean(MRo_c, na.rm = TRUE),
    mean_MRo_nc  = mean(MRo_nc, na.rm = TRUE),
    .groups = "drop"  
  )
# Convert summary table to long format for plotting
mobi_rate_region_summary_long <- mobi_rate_region_summary %>%
  pivot_longer(cols = c(mean_MRo_nc, mean_MRo_c), names_to = "variable", values_to = "value")

# Remove countries with missing region information
mobi_rate_country_region_no_NA<- mobi_rate_country %>%  filter(region != '#N/A' )


```


```{r}
#Draw Fig. 5-a
# Bar plot Fig. 5-a: average mobility rates by region (with and without prior international collaboration)

plot_mobi_rate_region<-ggplot(mobi_rate_region_summary_long, aes(x = factor(region, levels = c("East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa","North America","South Asia", "Sub-Saharan Africa")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4"), labels = c("mean_MRo_nc" = "Without prior international collaboration (MRo_nc)", 
                      "mean_MRo_c" = "With prior international collaboration (MRo_c)")) +
  
  scale_y_continuous(
    name = "Mean mobility rate", limits = c(0, 0.27), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2,0.25)
  ) +
    # Use region abbreviations for the x-axis
  
    scale_x_discrete(breaks = c( "East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa",
                                 "North America","South Asia","Sub-Saharan Africa"),
                     labels=c("EAP", "ECA", "LAC","MENA", "NA","SA","SSA")
                                )+
  scale_color_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4")) +
  
  labs(x = "Region of origin country") +
  guides(
    fill = guide_legend(title = NULL, ncol= 1),
    color = guide_legend(title = NULL, ncol = 1)
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),

    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 50),
    legend.position = c(0.6, 0.98)
  ) +
  ggtitle("a")

#Draw Fig. 5-b
# Violin and boxplot: distribution of CMR_o by region
plot_mobi_rate_region_box<-ggplot(mobi_rate_country_region_no_NA,aes(x=factor(region,levels=c("East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa","North America","South Asia","Sub-Saharan Africa")),y=CMR_o,fill = region))+
  geom_violin(size=2,width = 0.5,outlier.size=8)+
  geom_boxplot(size = 1.5, width = 0.2,outlier.size=8) +
  stat_boxplot(geom = "errorbar",size=3,width=0.2)+
  scale_fill_manual(values = c( 
    "East Asia & Pacific"="#1F77B4", 
                   "Europe & Central Asia"="#FF7F0E", 
                   "Latin America & Caribbean"="#2CA02C", 
                   "Middle East & North Africa"="#D62728", 
                   "North America"="#9467BD", 
                   "South Asia"= "#8c564b",
                   "Sub-Saharan Africa" = "#eeee00")) +
  

  stat_summary(fun=mean, geom="point", shape=23, size=15, fill="black")+
  guides(fill="none")+

  scale_y_continuous(limits= c(0,4),breaks=seq(0, 4,0.5))+
  scale_x_discrete(breaks = c(  "East Asia & Pacific", "Europe & Central Asia"
                                ,"Latin America & Caribbean","Middle East & North Africa"
                                ,"North America","South Asia","Sub-Saharan Africa"),
                   labels=c("EAP", "ECA", "LAC","MENA", "NA","SA","SSA")
                     )+
  xlab("Region of origin country")+
  ylab("Collaboration Mobility Ratio (CMR_o)")+

  theme_bw() +
    theme( legend.position = "none",

    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size=50),
    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.line.y=element_line(size=1.5,color='black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(30, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 30, 0, 0))

  )+
  ggtitle("b")
```


```{r}
# Calculate mean mobility rates by income group
mobi_rate_income_summary <- mobi_rate_country %>%
  group_by(income_group) %>%
  summarise(
    mean_MRo_c   = mean(MRo_c, na.rm = TRUE),
    mean_MRo_nc  = mean(MRo_nc, na.rm = TRUE),
    .groups = "drop" 
  )

# Convert summary table to long format for plotting

mobi_rate_income_summary_long <- mobi_rate_income_summary   %>%
  pivot_longer(cols = c(mean_MRo_nc, mean_MRo_c), names_to = "variable", values_to = "value")

# Remove countries with missing income group information

mobi_rate_country_income_no_NA<- mobi_rate_country %>%  filter(income_group != '#N/A')

```

```{r}
#Draw Fig. 5-c
# Bar plot: average mobility rates by income group (with/without prior international collaboration)
plot_mobi_rate_income<-ggplot(mobi_rate_income_summary_long  , aes(x = factor(income_group, levels = c("High", "Upper middle", "Lower middle", "Low")))) +
  geom_bar(aes(y = value, fill = variable), stat = "identity", position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4"), labels = c("mean_MRo_nc" = "Without prior international collaboration (MRo_nc)", 
                      "mean_MRo_c" = "With prior international collaboration (MRo_c)")) +
  
  scale_y_continuous(
    name = "Mean mobility rate", limits = c(0, 0.27), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2,0.25)
  ) +

  scale_color_manual(values = c("mean_MRo_nc" = "#d62728", "mean_MRo_c" = "#1f77b4"),
                    labels = c("mean_MRo_nc" = "Without prior international collaboration (MRo_nc)", 
                      "mean_MRo_c" = "With prior international collaboration (MRo_c)")) +
  scale_x_discrete(breaks = c( "High", "Upper middle", "Lower middle", "Low"),
                     labels=c("H", "UM", "LM", "L")
                                )+
  scale_y_continuous(
    name = "mean mobility rate", limits = c(0, 0.27), expand = c(0, 0), breaks = c(0, 0.05, 0.1, 0.15, 0.2,0.25)
  ) +
  labs(x = "Income group of origin country") +
  labs(y="Mobility rate")+
  guides(
    fill = guide_legend(title = NULL, ncol = 1),
    color = guide_legend(title = NULL, ncol = 1)
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title.position = "plot",  
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),

    axis.ticks = element_line(size = 1.5), 
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5), 
    axis.text = element_text(size = 50),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 50),
    legend.position = "none"
  )+
  ggtitle("c")

#Draw Fig. 5d
# Violin and boxplot: distribution of CMR_o by income group

plot_mobi_rate_income_box<-ggplot(mobi_rate_country_income_no_NA, aes(x = factor(income_group,levels = c("High", "Upper middle", "Lower middle", "Low")), y = CMR_o,fill = income_group)) +
  geom_violin(size=2,width = 0.5,outlier.size=8)+
  geom_boxplot(size = 1.5, width = 0.2,outlier.size=8) +
  stat_boxplot(geom = "errorbar",size=3,width=0.2)+
  
  scale_fill_manual(values = c(
    "High" = "#1f77b4",
    "Upper middle" = "#ff7f0e",
    "Lower middle" = "#2ca02c",
    "Low" = "#d62728"
  )) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 15, fill = "black") +
  guides(fill = "none") +
  scale_y_continuous(limits = c(0, 4), breaks = seq(0, 4, 0.5)) +
  scale_x_discrete(breaks = c("High", "Upper middle", "Lower middle", "Low"),
                   labels = c("H", "UM", "LM", "L")) +
  xlab("Income group of origin country") +
   ylab("Collaboration Mobility Ratio (CMR_o)")+
  theme_bw() +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(hjust = 0, vjust = 0, size = 80, face = "bold", color = "black"),
    strip.text = element_text(size = 50),
    axis.ticks = element_line(size = 1.5),
    axis.ticks.length = unit(0.5, "cm"),
    axis.line = element_line(size = 1.5),
    axis.text = element_text(size = 50),
    axis.line.y = element_line(size = 1.5, color = 'black'),
    axis.title = element_text(size = 50),
    axis.title.x = element_text(size = 50, margin = margin(30, 0, 0, 0)),
    axis.title.y = element_text(size = 50, margin = margin(0, 30, 0, 0))
  ) +
  ggtitle("d")

```

```{r}
# Save the combined plots (Fig. 5) as a PNG image

png(file="Fig QSS5--mobility rate_2023.png", width=3750,height=3000)

# Define the layout for a 4-panel figure
grid_layout <- rbind(
  c(1, 1, 1, 3, 3,3),
  c(1, 1, 1, 3, 3,3),
  c(2, 2, 2, 4, 4,4),
  c(2, 2, 2, 4, 4,4)
)

# Arrange the four plots in the specified layout
grid.arrange(plot_mobi_rate_region,           # 1: Bar plot by region
             plot_mobi_rate_income,           # 2: Bar plot by income group
             plot_mobi_rate_region_box,       # 3: Box/violin by region
             plot_mobi_rate_income_box,       # 4: Box/violin by income group
             layout_matrix = grid_layout)

dev.off() # Finish and save the image
```


```{r}
# Calculate average CMR_o and country count for each region and income group combination

CMR_region_income_summary <- mobi_rate_country %>%
  group_by(region, income_group) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n(),
            .groups = "drop"
            )
# Calculate average CMR_o and country count for each income group (region set as "Average")

CMR_income_summary <- mobi_rate_country %>%
  group_by(income_group) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n()) %>%
  mutate(region = "Mean")

# Calculate average CMR_o and country count for each region (income_group set as "Average")
CMR_region_summary <- mobi_rate_country %>%
  group_by(region) %>%
  summarise(mean_CMR_o = mean(CMR_o, na.rm = TRUE),
            country_count = n()) %>%
  mutate(income_group = "Mean")

# Combine all summaries into one table
CMR_region_income<-bind_rows(CMR_region_income_summary , CMR_income_summary, CMR_region_summary)

# Create a label with mean value and country count
CMR_region_income<- CMR_region_income %>%
  mutate(label = paste0(round(mean_CMR_o, 2), " (", country_count, ")"))

# Calculate overall mean and total number of records
total_mean_CMR_o <- mean(CMR_region_income$mean_CMR_o, na.rm = TRUE)
total_id_count <- nrow(CMR_region_income)

# Calculate the median mean_CMR_o across all region/income groups
median_value_region_income <- median(CMR_region_income$mean_CMR_o, na.rm = TRUE)

```


```{r}
# Save the heatmap (Fig. A2) as a PNG image
png(file="Fig QSS--A2--mobility rate--region and income.png", width=1500,height=500)

# Create a heatmap of mean_CMR_o for each region and income group
ggplot(CMR_region_income, aes(
  x = factor(income_group, levels = c("High", "Upper middle", "Lower middle", "Low","Mean")),
  y = factor(region, levels = c("Mean", "East Asia & Pacific", "Europe & Central Asia","Latin America & Caribbean","Middle East & North Africa",
                                 "North America","South Asia","Sub-Saharan Africa")), fill = mean_CMR_o)) +
  
# Main colored tiles for mean_CMR_o (excluding summary rows/columns)
   geom_tile(aes(fill = ifelse(income_group == "Mean" | region == "Mean", NA, mean_CMR_o)), color = "white") +
  
# White tiles for summary rows/columns (the "Average" cells)
  geom_tile(data = subset(CMR_region_income, income_group == "Mean" | region == "Mean"), fill = "white", color = "white") +
  
# Add label with mean value and country count to each cell

  geom_text(aes(label = label), color = "black", size = 8, 
            hjust = 0.5, vjust = 0.5) +
  
# Set color gradient for heatmap
  scale_fill_gradient2(low = "#ffffe0",  high = "#d62728")+
  labs( x = "Income group", y = "Region",fill = "mean_CMR_o")+
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), 
    plot.title = element_text(hjust = 0.5, size = 40),
    axis.ticks = element_blank(), 
    axis.ticks.length = unit(0, "cm"), 
    axis.text = element_text(size = 30),
    axis.title = element_blank(),
    axis.title.x = element_text(size = 30, margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(size = 30, margin = margin(0, 20, 0, 0)),
    axis.title.y.right = element_text(margin = margin(l = 20)),
    legend.text = element_text(size = 30),
      legend.title = element_blank(),
     # legend.title.align = 0.1,
    legend.key.size = unit(1, "cm"),           
    legend.key.width = unit(0.5, "cm"),       
    legend.key.height = unit(2, "cm")  ,     
      legend.position = "right"
  )
dev.off()  # Finish and save the image
```
